language: node_js
node_js:
  - '8'
  - '10'
  - '11'

notifications:
  email:
    on_success: never
    on_failure: always

script: yarn build

deploy:
  provider: npm
  email: npm@jupiterone.io
  api_key:
    secure: "bL3Qr7fxC43iuDN0DaTtLfnHSfPDaEwQ/33c0laKNyejlF1CB7KsIE+AyDz1f6xHvp6gWIfxvWS/2gmtBERlHQmvzK/vsPeKKBiW4Aob6/v1FKtY4clparNjrgaVaBGvmbrzKzUJ6XrqhZcuGNV0t8F7l/e5UQsF9zAv+ADMol8dGj8d6wvCU5JVt1Dm0zTJMmwE60UWthohiXGEReKQHjiofbnWcEwf6d1lluKudwyGyjUdWPbSF37h+k+/JnblHP/Q6G9F29iE04dQuE0qh6wAG8yVoaf2CNGpqdbTZ/cXjuF4s93IBjuVvPcDervTk3NdBTLZEdgEYc3WX81uuBWIkcSoxDL317/uwoO01Fto8gkl5tIglFiEA6rLSb5/OuE4x9mKLP6c92UegT50MeQONlpOzfGU38yGgniwKVlZxMS+Ka25DtiiknmDrDHj7HYcYr+2usz/2J8G9yCfLMCz/S2+RN+f4NHVmNM4E01oAcYluHHeO2jNd5XghU3hcXgjzA6LZ6r8FRg1/0MfefRqendltQW9ANsm5pnW8QjymGJ7L3/xOPgtA61evRijendWGiOjPvAzC4L58X5W0573bo2sBd5Qw/QxosiMJ6AzHpf2Twlu3SkrbeFsQQHtHV63WLoHDZSf59oMynjiKFGprG73Edd3/p9cpB6Opb8="
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: JupiterOne/jupiter-integration-azure
    node: '8'
