version: "3.7"

services:
  integration:
    image: graph-azure-app
    build: .
    container_name: graph-azure-app
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    environment:
      NODE_ENV: development
      GRAPH_DB_ENDPOINT: graph
      AZURE_CLOUD_LOCAL_EXECUTION_CLIENT_ID: "Yor Application (client) ID"
      AZURE_CLOUD_LOCAL_EXECUTION_CLIENT_SECRET:
        "One of the yor app's client secret"
      AZURE_CLOUD_LOCAL_EXECUTION_DIRECTORY_ID: "Directory (tenant) ID"
    depends_on:
      - graph
  graph:
    image: tinkerpop/gremlin-server:3.3
    restart: unless-stopped
    ports:
      - "8182:8182"
